# Generated by Django 5.2.5 on 2025-11-26 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_guests_booking_special_requests_and_more'),
        ('payments', '0002_rename_reference_payment_pesapal_merchant_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='pesapal_transaction_tracking_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='raw_response',
        ),
        migrations.AddField(
            model_name='payment',
            name='pesapal_order_tracking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
