# Generated by Django 5.2.5 on 2025-11-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_roomreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservice',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='service_icons/'),
        ),
    ]
