# Generated by Django 5.2.5 on 2025-12-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_guests_booking_special_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
